### ISSUE TITLE
12.4 Breaking Change Sending Include to Custom LWRP

### ISSUE THREAD

**Issue by dpetzel** [chef/chef#3607]
This was originally discussed in http://lists.opscode.com/sympa/arc/chef-dev/2015-06/msg00039.html.

we are seeing several CI jobs failing for cookbooks with errors like this:
```
NoMethodError
         -------------
         undefined method `a_method_in_my_library' for LWRP resource my_lwrp from cookbook my_cookbook
```

Reading through https://www.chef.io/blog/2015/06/24/chef-client-12-4-0-released/ (the section titled "LWRPs are no longer automatically placed in the Chef::Resource namespace") seems to be the key info. This implies it should be nothing more than a deprecation, however it seems to be causing an actual failure. Here is a snippet of what we are doing:
```
::Chef::Resource::MyLwrp.send(:include, ::My::Module)
my_lwrp 'blah' do
  resource_file a_method_in_my_library
end
```

This works fine on 12.3.0 and only started failing as of 12.4.0. This feels like a pretty common pattern and I think the deprecation message is fine, but feels like this should continue to work in 12.4.0?

I've whipped up an example cookbook that illustrates the issue here: https://github.com/dpetzel/chef_12_4_lwrp_method_include

**Comment by coderanger** [comment]
This is not a good pattern, you should put the include in the LWRP itself.

**Comment by jaym** [comment]
https://github.com/chef/chef/pull/3603

**Comment by dpetzel** [comment]
@coderanger Thanks, just to clarify, when you say in the LWRP itself, your referring to block invoking the LWPR, not actually inside the resource/provider .rb files?

@ranjib turned me onto this format (which works), is this what you had in mind?
```
my_lwrp 'blah' do
  extend ::My::Module
  resource_file a_method_in_my_library
end
```
I'm curious though whats wrong with the current approach, and how/why is the extend method (or some other alternative) are better? I'm not real solid in Ruby so I'm asking not because I doubt what you say, just that I'd like to better understand it.

Thanks

**Comment by coderanger** [comment]
No, I mean in the `resource/whatever.rb`. Add `include ::My::Module` to the top of the file, it will have the same effect.

**Comment by dpetzel** [comment]
That won't work when the LWRP is defined in another cookbook though Which is actually the pattern we use this pattern in (In hindsight my example should have illustrated that). When consuming an LWRP from another cookbook we send methods from this cookbooks libraries so we can call those methods directly inside the block as opposed to setting a variable outside the block and then referencing the variable.

**Comment by coderanger** [comment]
Monkey-patching code from another cookbook should be done with the same level of "this is a bad idea and we're only doing it for a week" as all other global patching. A better fix would probably be an ad-hoc subclass, though this is trickier with LWRPs (and is a great reason to never use them in shared cookbooks :). That said, #3603 will fix your code, but I highly recommend something like this instead:

```ruby
class MySubclass < Chef::ResourceResolver.resolve(:other_lwrp)
  provides(:my_subclass)
  include ::My::Module
end
```

Unfortunately due to how the Chef load order works, you can't put that in a `libraries/` file like you normally would, it has to go in your recipe, but otherwise it should work as normal and avoids the monkeypatching.

**Comment by dpetzel** [comment]
@coderanger Thanks, I'll give that approach a spin.

**Comment by lamont-granquist** [comment]
#3603 is merged
