### ISSUE TITLE
if Chef Client run fails early, run_id is undefined and throws an error

### ISSUE THREAD

**Issue by juliandunn** [chef/chef#2996]
If you do something like start a Chef Client run without a `validation.pem` or `client.pem` and the run explodes early, a message is still printed at the very end:

```FATAL: NoMethodError: undefined method `run_id` for nil:NilClass```

Unfortunately the stacktrace.out doesn't give any indication about where this is happening, given that it's obscured with the error about the missing key.

**Comment by gretel** [comment]
same issue on windows using chef 12.1.0

**Comment by btm** [comment]
git bisect lead to https://github.com/chef/chef/commit/f83e13f6aae353533cfff74a0adc71a5f91673a6

**Comment by lamont-granquist** [comment]
looks like fixed in 12.3.0
