### ISSUE TITLE
custom resources fail after upgrade to Chef Infra Client 16.2.44

### ISSUE THREAD

**Issue by grdz** [chef/chef#10016]
## Description
I am using managed_directory cookbook from Supermarket ( https://supermarket.chef.io/cookbooks/managed_directory ). It was working in Chef Infra 16.1. After upgrade to 16.2.44 I can not use `depends cookbook_name` in metadata.rb and then use its custom resource in recipe since I got:

`[2020-06-18T09:50:06+02:00] FATAL: NoMethodError: undefined method `managed_directory' for cookbook: cookbook_name, recipe: recipe_name :Chef::Recipe`

I tried adding `include_recipe 'managed_directory'` in the recipe in which I am trying to use the managed_directory resource, but to no avail.

## Chef Version
16.2.44

## Platform Version
CentOS 7

## Replication Case
I believe that you just need to try and use custom resource cookbook and try to use its resource in a recipe.

## Client Output

```
/var/chef/cache/cookbooks/cookbook_name/recipes/recipe_name.rb:

 84>> managed_directory '/directory' do
 85:    action :clean
 86:    clean_directories true
 87:    clean_links true
 88:    clean_files true
 89:  end

System Info:
------------
chef_version=16.2.44
platform=cloudlinux
platform_version=7.8
ruby=ruby 2.7.1p83 (2020-03-31 revision a0c7c23c9c) [x86_64-linux]
program_name=/usr/bin/chef-client
executable=/opt/chef/bin/chef-client


Running handlers:
[2020-06-18T09:50:06+02:00] ERROR: Running exception handlers
Running handlers complete
[2020-06-18T09:50:06+02:00] ERROR: Exception handlers complete
Chef Infra Client failed. 0 resources updated in 34 seconds
[2020-06-18T09:50:06+02:00] FATAL: Stacktrace dumped to /var/chef/cache/chef-stacktrace.out
[2020-06-18T09:50:06+02:00] FATAL: Please provide the contents of the stacktrace.out file if you file a bug report
[2020-06-18T09:50:06+02:00] DEBUG: NoMethodError: undefined method `managed_directory' for cookbook: cookbook_name, recipe: recipe_name :Chef::Recipe
/var/chef/cache/cookbooks/cookbook_name/recipes/recipe_name.rb:84:in `from_file'
/opt/chef/embedded/lib/ruby/gems/2.7.0/gems/chef-16.2.44/lib/chef/mixin/from_file.rb:34:in `instance_eval'
/opt/chef/embedded/lib/ruby/gems/2.7.0/gems/chef-16.2.44/lib/chef/mixin/from_file.rb:34:in `from_file'
/opt/chef/embedded/lib/ruby/gems/2.7.0/gems/chef-16.2.44/lib/chef/cookbook_version.rb:230:in `load_ruby_recipe'
/opt/chef/embedded/lib/ruby/gems/2.7.0/gems/chef-16.2.44/lib/chef/cookbook_version.rb:200:in `load_recipe'
/opt/chef/embedded/lib/ruby/gems/2.7.0/gems/chef-16.2.44/lib/chef/run_context.rb:393:in `load_recipe'
/opt/chef/embedded/lib/ruby/gems/2.7.0/gems/chef-16.2.44/lib/chef/run_context.rb:349:in `block in include_recipe'
/opt/chef/embedded/lib/ruby/gems/2.7.0/gems/chef-16.2.44/lib/chef/run_context.rb:348:in `each'
/opt/chef/embedded/lib/ruby/gems/2.7.0/gems/chef-16.2.44/lib/chef/run_context.rb:348:in `include_recipe'
/opt/chef/embedded/lib/ruby/gems/2.7.0/gems/chef-16.2.44/lib/chef/dsl/include_recipe.rb:26:in `include_recipe'
/var/chef/cache/cookbooks/cookbook_name/recipes/default.rb:43:in `from_file'
/opt/chef/embedded/lib/ruby/gems/2.7.0/gems/chef-16.2.44/lib/chef/mixin/from_file.rb:34:in `instance_eval'
/opt/chef/embedded/lib/ruby/gems/2.7.0/gems/chef-16.2.44/lib/chef/mixin/from_file.rb:34:in `from_file'
/opt/chef/embedded/lib/ruby/gems/2.7.0/gems/chef-16.2.44/lib/chef/cookbook_version.rb:230:in `load_ruby_recipe'
/opt/chef/embedded/lib/ruby/gems/2.7.0/gems/chef-16.2.44/lib/chef/cookbook_version.rb:200:in `load_recipe'
/opt/chef/embedded/lib/ruby/gems/2.7.0/gems/chef-16.2.44/lib/chef/run_context.rb:393:in `load_recipe'
/opt/chef/embedded/lib/ruby/gems/2.7.0/gems/chef-16.2.44/lib/chef/run_context/cookbook_compiler.rb:174:in `block in compile_recipes'
/opt/chef/embedded/lib/ruby/gems/2.7.0/gems/chef-16.2.44/lib/chef/run_context/cookbook_compiler.rb:171:in `each'
/opt/chef/embedded/lib/ruby/gems/2.7.0/gems/chef-16.2.44/lib/chef/run_context/cookbook_compiler.rb:171:in `compile_recipes'
/opt/chef/embedded/lib/ruby/gems/2.7.0/gems/chef-16.2.44/lib/chef/run_context/cookbook_compiler.rb:79:in `compile'
/opt/chef/embedded/lib/ruby/gems/2.7.0/gems/chef-16.2.44/lib/chef/run_context.rb:223:in `load'
/opt/chef/embedded/lib/ruby/gems/2.7.0/gems/chef-16.2.44/lib/chef/policy_builder/expand_node_object.rb:103:in `setup_run_context'
/opt/chef/embedded/lib/ruby/2.7.0/forwardable.rb:235:in `setup_run_context'
/opt/chef/embedded/lib/ruby/gems/2.7.0/gems/chef-16.2.44/lib/chef/client.rb:498:in `setup_run_context'
/opt/chef/embedded/lib/ruby/gems/2.7.0/gems/chef-16.2.44/lib/chef/client.rb:284:in `run'
/opt/chef/embedded/lib/ruby/gems/2.7.0/gems/chef-16.2.44/lib/chef/application.rb:292:in `run_with_graceful_exit_option'
/opt/chef/embedded/lib/ruby/gems/2.7.0/gems/chef-16.2.44/lib/chef/application.rb:268:in `block in run_chef_client'
/opt/chef/embedded/lib/ruby/gems/2.7.0/gems/chef-16.2.44/lib/chef/local_mode.rb:42:in `with_server_connectivity'
/opt/chef/embedded/lib/ruby/gems/2.7.0/gems/chef-16.2.44/lib/chef/application.rb:251:in `run_chef_client'
/opt/chef/embedded/lib/ruby/gems/2.7.0/gems/chef-16.2.44/lib/chef/application/base.rb:335:in `run_application'
/opt/chef/embedded/lib/ruby/gems/2.7.0/gems/chef-16.2.44/lib/chef/application.rb:68:in `run'
/opt/chef/embedded/lib/ruby/gems/2.7.0/gems/chef-bin-16.2.44/bin/chef-client:25:in `<top (required)>'
/usr/bin/chef-client:162:in `load'
/usr/bin/chef-client:162:in `<main>'
[2020-06-18T09:50:06+02:00] FATAL: NoMethodError: undefined method `managed_directory' for cookbook: cookbook_namel, recipe: recipe_name :Chef::Recipe

```

**Comment by lamont-granquist** [comment]
That's documented as a breaking change in the 16.2 release notes:

https://discourse.chef.io/t/chef-infra-client-16-2-released/17284

The change is here:

https://github.com/chef/chef/pull/9890

The issue with Chef 16.0 which prompted the change is linked in the ticket:

https://github.com/chef/chef/issues/9885

The reason why fixing #9885 was necessary this way was that it clearly is getting used and affects people AND the fact that anyone who hits that bug is going to need to talk to me, specifically, as the one person in the world to help them fix it -- which is unacceptable since I don't scale.  The alternative change in #9890 gets us to a world where the behavior is simple and the break is easily understandable, and where a cookstyle rule can be written to identify and fix the issue:

https://github.com/chef/cookstyle/blob/master/lib/rubocop/cop/chef/deprecation/resource_uses_only_resource_name.rb

We could not go 11 months without being able to cookstyle a rule to fix #9885, and forever have that as a blocker to people upgrading to 16 where cookstyle could never get them over the hurdle.

**Comment by grdz** [comment]
@lamont-granquist thanks for reply. I am trying to wrap my head around this. In other words, can I fix it by calling custom resource from other cookbook in some other way, or do I need to modify the cookbook with custom resource?
