### ISSUE TITLE
Using password property for execute resource on Windows

### ISSUE THREAD

**Issue by rneu31** [chef/chef#6187]
## Description
Using the password property on Windows results in 
```
 NoMethodError
 -------------
 undefined method `password' for Chef::Resource::Execute

 Platform:
 ---------
 x64-mingw32
```

Also noticed similar behavior if using the `domain` property.

## Chef Version

Chef Client v12.18.31

## Platform Version

Windows 10 64-bit

**Comment by lamont-granquist** [comment]
You have to to be using 12.19.36 to use that.  It was only introduced in c6e87d9655617d7d4b334b3e565cdac3abe443b0.
