### ISSUE TITLE
Local mode of Chef Client 12.7.2 fails on cookbook sync step

### ISSUE THREAD

**Issue by legal90** [chef/chef#4575]
I've reproduced it via TestKitchen on with `policyfile_zero` provisioner.
Converge works fine on 12.6.0, but after update to 12.7.2 it fails on early stage:
```
-----> Chef Omnibus installation detected (install only if missing)
       Transferring files to <consul-foo-centos-6>
       Starting Chef Client, version 12.7.2
       Creating a new client identity for consul-foo-centos-6 using the validator key.
       Using policy 'consul-foo' at revision '6632a112c15e007d2f99a8eccb9248a02c77d493a62593b07e647290c92c2c71'
       resolving cookbooks for run list: ["env-consul::default@0.2.1 (80e604b)"]

       ================================================================================
       Error Syncing Cookbooks:
       ================================================================================

       Unexpected Error:
       -----------------
       NoMethodError: undefined method `name' for #<Hash:0x00000002383d38>


       Running handlers:
       [2016-02-13T11:48:28-08:00] ERROR: Running exception handlers
       Running handlers complete
       [2016-02-13T11:48:28-08:00] ERROR: Exception handlers complete
       Chef Client failed. 0 resources updated in 02 seconds
       [2016-02-13T11:48:28-08:00] FATAL: Stacktrace dumped to /tmp/kitchen/cache/chef-stacktrace.out
       [2016-02-13T11:48:28-08:00] FATAL: Please provide the contents of the stacktrace.out file if you file a bug report
       [2016-02-13T11:48:28-08:00] ERROR: undefined method `name' for #<Hash:0x00000002383d38>
       [2016-02-13T11:48:30-08:00] FATAL: Chef::Exceptions::ChildConvergeError: Chef run process exited unsuccessfully (exit code 1)
>>>>>> Converge failed on instance <consul-foo-centos-6>.
>>>>>> Please see .kitchen/logs/consul-foo-centos-6.log for more details
>>>>>> ------Exception-------
>>>>>> Class: Kitchen::ActionFailed
>>>>>> Message: SSH exited (1) for command: [sh -c '

sudo -E /opt/chef/bin/chef-client --local-mode --config /tmp/kitchen/client.rb --log_level auto --force-formatter --no-color --chef-zero-port 8889
']
>>>>>> ----------------------
```

And here is the content of `/tmp/kitchen/cache/chef-stacktrace.out`:
```
Generated at 2016-02-13 12:58:37 -0800
NoMethodError: undefined method `name' for #<Hash:0x000000037a3c28>
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.7.2/lib/chef/cookbook/synchronizer.rb:144:in `block in sync_cookbooks'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.7.2/lib/chef/cookbook/synchronizer.rb:144:in `map'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.7.2/lib/chef/cookbook/synchronizer.rb:144:in `sync_cookbooks'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.7.2/lib/chef/policy_builder/policyfile.rb:187:in `sync_cookbooks'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.7.2/lib/chef/policy_builder/policyfile.rb:153:in `setup_run_context'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.7.2/lib/chef/client.rb:509:in `setup_run_context'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.7.2/lib/chef/client.rb:277:in `run'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.7.2/lib/chef/application.rb:270:in `block in fork_chef_client'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.7.2/lib/chef/application.rb:258:in `fork'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.7.2/lib/chef/application.rb:258:in `fork_chef_client'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.7.2/lib/chef/application.rb:223:in `block in run_chef_client'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.7.2/lib/chef/local_mode.rb:44:in `with_server_connectivity'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.7.2/lib/chef/application.rb:211:in `run_chef_client'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.7.2/lib/chef/application/client.rb:433:in `block in interval_run_chef_client'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.7.2/lib/chef/application/client.rb:423:in `loop'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.7.2/lib/chef/application/client.rb:423:in `interval_run_chef_client'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.7.2/lib/chef/application/client.rb:412:in `run_application'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.7.2/lib/chef/application.rb:58:in `run'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.7.2/bin/chef-client:26:in `<top (required)>'
/opt/chef/bin/chef-client:50:in `load'
/opt/chef/bin/chef-client:50:in `<main>'
```

Actually, in 12.7.2, `cookbooks` [here](https://github.com/chef/chef/blob/cb4ee84e418164e8d2e85147efad711a42ff2799/lib/chef/cookbook/synchronizer.rb#L144) is an array of Hash'es. But in 12.6.0 it is an array of `Chef::CookbookVersion` instances and it appears to be an expected value.

Probably, it's caused by this condition: https://github.com/chef/chef/blob/d99e306a41b1402209d320cb7119b12a3bbb962f/lib/chef/policy_builder/policyfile.rb#L438-L444

cc: @danielsdeleo

**Comment by legal90** [comment]
Oops, sorry. It's already fixed by https://github.com/chef/chef/pull/4571
