### ISSUE TITLE
Package remove fails on SLES without version number

### ISSUE THREAD

**Issue by splap** [chef/chef#1732]
##### Scenario:

If you remove a package during a chef-client run on a SLES box, the remove action fails when package version is not specified.

The problem was addressed [in this pull request](https://github.com/opscode/chef/pull/1174), but it was missing a unit test.
##### Versions:

11.6.0-1.el5
11.8.0

Scenario works with 10.18.2-2
##### Environment:

Repro OS: SUSE Linux version 3.0.80-0.7-pae
Unit test: OS X
##### Steps to Reproduce:
1. Spin up a SLES VM with chef-client 11.6 installed
2. Create a cookbook which installs a package
3. Run chef-client on the VM with cookbook from step 2 in run list
4. Update the cookbook to remove the package
##### Expected Result:

The package is uninstalled, unit test passes
##### Actual Result:

chef-client fails:

```
Error executing action 'remove' on resource 'package[SOMEPACKAGE]'"

NoMethodError: undefined method 'empty?' for nil:NilClass
/opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.6.0/lib/chef/provider/package/zypper.rb:109:in 'zypper_package'`
/opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.6.0/lib/chef/provider/package/zypper.rb:100:in `remove_package'
/opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.6.0/lib/chef/provider/package.rb:105:in `block in action_remove'
/opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.6.0/lib/chef/mixin/why_run.rb:52:in `call'
/opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.6.0/lib/chef/mixin/why_run.rb:52:in `add_action'
/opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.6.0/lib/chef/provider.rb:149:in `converge_by'
/opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.6.0/lib/chef/provider/package.rb:104:in `action_remove'
/opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.6.0/lib/chef/provider.rb:114:in `run_action'
/opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.6.0/lib/chef/resource.rb:625:in `run_action'
```
