### ISSUE TITLE
Attribute dependency 

### ISSUE THREAD

**Issue by YpNo** [chef/chef#7900]
## Description
Compilation error when you need to have cross attribute dependency between two cookbooks. It doesn't resolve/found dependency attribute when you call a cookbook which depends on an other cookbook which himself call an attribute of first cookbook

## Chef Version
tested with v14.5.27 and higher

## Platform Version
Debian 8

## Replication Case
I have 2 cookbooks. Each depends to the other in metadata

```
cookbooks/cb1
├── attributes
│   └── default.rb
├── metadata.rb
├── recipes
│   └── default.rb
```

```
cookbooks/cb2
├── attributes
│   └── default.rb
├── metadata.rb
├── recipes
│   └── default.rb
```

cookbooks/cb1/attributes/default.rb
`default['cb1']['port'] = '1234'`

cookbooks/cb1/recipes/default.rb
```
puts "CB1: #{node['cb1']['port']}"
puts "CB1: #{node['cb2']['service']}"
```

cookbooks/cb2/attributes/default.rb
`default['cb2']['service'] = "service_cb2:#{node['cb1']['port']}"`

Add into run_list: recipe['cb1']

## Client Output

```
...
==> jessie: Synchronizing Cookbooks:
==> jessie: - cb1 (0.1.0)
==> jessie:   - cb2 (0.1.0)
==> jessie: Installing Cookbook Gems:
==> jessie: Compiling Cookbooks...
==> jessie: 
==> jessie: ================================================================================
==> jessie: Recipe Compile Error in /var/chef/cache/cookbooks/cb2/attributes/default.rb
==> jessie: ================================================================================
==> jessie: 
==> jessie: NoMethodError
==> jessie: -------------
==> jessie: undefined method `[]' for nil:NilClass
==> jessie: 
==> jessie: Cookbook Trace:
==> jessie: ---------------
==> jessie:   /var/chef/cache/cookbooks/cb2/attributes/default.rb:1:in `from_file'
==> jessie: 
==> jessie: Relevant File Content:
==> jessie: ----------------------
==> jessie: /var/chef/cache/cookbooks/cb2/attributes/default.rb:
==> jessie: 
==> jessie:   1>> default['cb2']['service'] = "service_cb2:#{node['cb1']['port']}"
==> jessie:   2:  
==> jessie: 
==> jessie: 
==> jessie: System Info:
==> jessie: ------------
==> jessie: chef_version=14.5.27
==> jessie: platform=debian
==> jessie: platform_version=8.11
==> jessie: ruby=ruby 2.5.1p57 (2018-03-29 revision 63029) [x86_64-linux]
==> jessie: program_name=/usr/bin/chef-client
==> jessie: executable=/opt/chef/bin/chef-client
==> jessie: 
==> jessie: 
==> jessie: 
==> jessie: Running handlers:
==> jessie: [2018-11-08T21:31:35+00:00] ERROR: Running exception handlers
==> jessie: Running handlers complete
==> jessie: 
==> jessie: [2018-11-08T21:31:35+00:00] ERROR: Exception handlers complete
==> jessie: Chef Client failed. 0 resources updated in 45 seconds
==> jessie: [2018-11-08T21:31:35+00:00] FATAL: Stacktrace dumped to /var/chef/cache/chef-stacktrace.out
==> jessie: [2018-11-08T21:31:35+00:00] FATAL: Please provide the contents of the stacktrace.out file if you file a bug report
==> jessie: [2018-11-08T21:31:35+00:00] FATAL: NoMethodError: undefined method `[]' for nil:NilClass
Chef never successfully completed! Any errors should be visible in the
output above. Please fix your recipes so that they properly complete.
```

**Comment by YpNo** [comment]
Up.

**Comment by lamont-granquist** [comment]
> I have 2 cookbooks. Each depends to the other in metadata

that creates a circular dependency which causes problems.  its is a poor way to structure code, it gives depsolvers performance issues, and causes logical difficulties like the one you've got now.  it is difficult for chef itself to ban, but its a very bad practice that would be banned if it was simple to do so.  the molinillo depsolver in policyfiles and with berkshelf will also fail to upload these files, and i think i've included code now in berkshelf which attempts to fail to upload circular deps even with the gecode solver.

cb2 needs to depend on cb1 and the dependency of cb1 on cb2 needs to be removed.  then cb1 will have its attributes file parsed first, before cb2's attributes file.  right now you're getting the reverse order.

you can also see also noah's blog on this subject where he goes into the problem in more detail:  https://coderanger.net/derived-attributes/
