### ISSUE TITLE
Unknown reversion on master

### ISSUE THREAD

**Issue by coderanger** [chef/chef#3692]
Started getting a [failure this morning on my master builds](https://travis-ci.org/poise/poise-service-runit/jobs/71899472). This looks to be an issue in the runit cookbook, specifically [the `#owner` property](https://github.com/hw-cookbooks/runit/blob/v1.6.0/libraries/resource_runit_service.rb#L155-L157). It also looks like nightly builds were down for two weeks, so I can only narrow this to "some time between 12.4.1 and yesterday". The actual exception is `undefined method 'match' for [/^[^-+~:,\t\r\n\f\0]+[^:,\t\r\n\f\0]*$/]:Array`, which makes me think the value passed to `_pv_regex` is nested too deeply, which matches what I see in the code, the [`user_valid_regex` is itself an array](https://github.com/chef/chef/blob/master/chef-config/lib/chef-config/config.rb#L561) so putting that in an array like the runit cookbook does would be nesting too deeply. The question then is why does this work in 12.4.1? I can't find the code change that actually broke things.

**Comment by coderanger** [comment]
Ping @thommay @jkeiser @lamont-granquist

**Comment by adamedx** [comment]
@jaym, have you seen this? I see plenty of green pr's so I'm a little confused.

**Comment by jaym** [comment]
will look into it

**Comment by jaym** [comment]
```
       Installing Chef 12.5.0-current.0%2B20150721082808.git.14.c91b337-1
       installing with dpkg...
       Selecting previously unselected package chef.
(Reading database ... 47562 files and directories currently installed.)
       Unpacking chef (from .../chef_12.5.0~current.0%2B20150721082808.git.14.c91b337-1_amd64.deb) ...
       Setting up chef (12.5.0~current.0+20150721082808.git.14.c91b337-1) ...
       Thank you for installing Chef!
       Processing triggers for initramfs-tools ...
       update-initramfs: Generating /boot/initrd.img-3.2.0-87-virtual
       Transferring files to <service-ubuntu-1204-ubuntu-1204>
       Starting Chef Client, version 12.5.0.current.0
       Creating a new client identity for service-ubuntu-1204-ubuntu-1204 using the validator key.
       [2015-07-23T16:34:16+00:00] WARN: Child with name 'dna.json' found in multiple directories: /tmp/kitchen/dna.json and /tmp/kitchen/dna.json
       [2015-07-23T16:34:16+00:00] WARN: Child with name 'dna.json' found in multiple directories: /tmp/kitchen/dna.json and /tmp/kitchen/dna.json
       resolving cookbooks for run list: ["apt", "runit_test::service"]
       [2015-07-23T16:34:16+00:00] WARN: Child with name 'dna.json' found in multiple directories: /tmp/kitchen/dna.json and /tmp/kitchen/dna.json
       Synchronizing Cookbooks:
         - apt
         - runit_test
         - runit_other_test
         - runit
         - packagecloud
       Compiling Cookbooks...

       ================================================================================
       Recipe Compile Error in /tmp/kitchen/cache/cookbooks/runit_test/recipes/service.rb
       ================================================================================

       NoMethodError
       -------------
       undefined method `match' for [/^[^-+~:,\t\r\n\f\0]+[^:,\t\r\n\f\0]*$/]:Array

       Cookbook Trace:
       ---------------
         /tmp/kitchen/cache/cookbooks/runit/libraries/resource_runit_service.rb:166:in `owner'
         /tmp/kitchen/cache/cookbooks/runit_test/recipes/service.rb:115:in `block in from_file'
         /tmp/kitchen/cache/cookbooks/runit_test/recipes/service.rb:112:in `from_file'

       Relevant File Content:
       ----------------------
       /tmp/kitchen/cache/cookbooks/runit/libraries/resource_runit_service.rb:

       159:        end
       160:
       161:        def delete_downfile(arg = nil)
       162:          set_or_return(:delete_downfile, arg, :kind_of => [TrueClass, FalseClass])
       163:        end
       164:
       165:        def owner(arg = nil)
       166>>         set_or_return(:owner, arg, regex: [Chef::Config[:user_valid_regex]])
       167:        end
       168:
       169:        def group(arg = nil)
       170:          set_or_return(:group, arg, regex: [Chef::Config[:group_valid_regex]])
       171:        end
       172:
       173:        def default_logger(arg = nil)
       174:          set_or_return(:default_logger, arg, kind_of: [TrueClass, FalseClass])
       175:        end


       Running handlers:
       [2015-07-23T16:34:25+00:00] ERROR: Running exception handlers
       Running handlers complete
       [2015-07-23T16:34:25+00:00] ERROR: Exception handlers complete
       Chef Client failed. 0 resources updated in 11.599310756 seconds
       [2015-07-23T16:34:25+00:00] FATAL: Stacktrace dumped to /tmp/kitchen/cache/chef-stacktrace.out
       [2015-07-23T16:34:25+00:00] ERROR: undefined method `match' for [/^[^-+~:,\t\r\n\f\0]+[^:,\t\r\n\f\0]*$/]:Array
       [2015-07-23T16:34:25+00:00] FATAL: Chef::Exceptions::ChildConvergeError: Chef run process exited unsuccessfully (exit code 1)
```

**Comment by jkeiser** [comment]
It could be that the property rewrite has a bug with deeply nested arrays in regex. Looking.

**Comment by jkeiser** [comment]
@coderanger @jaym I think the above PR fixes the issue.

**Comment by coderanger** [comment]
Yep, and for comparison the original code did have a flatten: https://github.com/chef/chef/blob/12.4.0/lib/chef/mixin/params_validate.rb#L205

```
[ regex ].flatten.each do |r|
```

**Comment by jkeiser** [comment]
Yep!  I don't think this was the original purpose of the `flatten`, but it's best to be compatible.
