### ISSUE TITLE
12.5 regressions

### ISSUE THREAD

**Issue by jaymzh** [chef/chef#3897]
While trying to test @lamont-granquist 's new attribute code, I also was playing around with 12.5 current and noticed that code we have in a provider that does:

```
def load_current_resource
  @current_resource.foo = false
end
...

action :foo do
  execute 'something' do
    only_if { current_resource.foo }
  end
end
```

Fails with `undefined method 'foo' for nil:NilClass` - but works in 12.4.1

**Comment by lamont-granquist** [comment]
Looks like it might be related to resources and maybe @jkeiser?

The unsimplified example had some references to Mixlib::ShellOut so I was wondering if it might have something to do with @jaym's changes, but if the simplified example fails like that it's probably nothing to do with that...

**Comment by lamont-granquist** [comment]
Tagging @thommay as well.

**Comment by coderanger** [comment]
I think we changed the binding context on not_if/only_if? Can you check if this works?

```ruby
action :foo do
  r = current_resource
  execute 'something' do
    only_if { r.foo }
  end
end
```

If that still works, it would definitely point at a context issue, or something with the enclosing_provider forwarding code.

**Comment by jkeiser** [comment]
I suspect it has to do with [this](https://github.com/chef/chef/blob/master/lib/chef/resource.rb#L1413). I'll take a look at a patch when my head clears.

**Comment by adamedx** [comment]
@mcquin is going to have a look.

**Comment by lamont-granquist** [comment]
So the problem is that adding Chef::Resource::Execute#current_resource has shadowed over the outer Chef::Provider#current_resource in the binding.

Can we rename Chef::Resource#current_resource instead of ripping it out, or think of some other solution?

**Comment by jaymzh** [comment]
This is still broken with the latest nightly.

chef-12.5.0~current.0+20150821082812.git.165.c832f38-1.el6.x86_64

**Comment by lamont-granquist** [comment]
nightlies are busted right now, that's 8/21, not 9/21...

**Comment by jaymzh** [comment]
ah. well... if someone wants to throw a nightly at me I can test. Should the 12.4.2 RPM I was testing for Mathilde include this?

**Comment by jkeiser** [comment]
@jaymzh try http://opscode-omnibus-packages-current.s3.amazonaws.com/el/6/x86_64/chef-12.5.0~current.0+20150909213019.git.314.9cf93f1-1.el6.x86_64.rpm

**Comment by jaymzh** [comment]
@jkeiser `ERROR 404: Not Found`

**Comment by jkeiser** [comment]
@jaymzh updated url above, didn't translate the + :)

**Comment by jkeiser** [comment]
@jaymhz also, regarding 12.4.1/2, that shouldn't have the bug in the first place (let us know if it does!).

**Comment by jaymzh** [comment]
Still 404.

**Comment by jaymzh** [comment]
ah URL works now. will let you know if the build works. Thanks

**Comment by jaymzh** [comment]
Er - this fails cause of RPM regressions:

```
error: Failed dependencies:
	rpmlib(TildeInVersions) <= 4.10.0-1 is needed by chef-12.5.0~current.0+20150909213019.git.314.9cf93f1-1.el6.x86_64
```

CC @MathildeBarr

**Comment by MathildeBarr** [comment]
cc @andy-dufour @irvingpop

**Comment by jkeiser** [comment]
@jaymzh can you try it out of master? The tilde thing is being tracked elsewhere, and I'd like to find out if this particular bug is fixed. We will make sure there is an rc or beta you can use that has no tilde.

**Comment by jaymzh** [comment]
I can... though it's not a terribly conducive environment for that being a weird embedded yocto linux build on a switch... so it takes some wrangling. I have wall to wall meetings today, but I'll try to get to it today or tomorrow.

**Comment by jkeiser** [comment]
@jaymhz we made a change to the nightly that might be able to get you a non-tilde one later today--stay tuned.

**Comment by jkeiser** [comment]
@jaymzh actually, I think this one *likely* has the fix (it's a close thing, @claire checked in the fix that day and this was produced that night): http://opscode-omnibus-packages-current.s3.amazonaws.com/el/6/x86_64/chef-12.5.0+20150918085109-1.el6.x86_64.rpm

If you'd like to give that a whirl. I believe the build system will spit us out a new build in an hour or two, though, and will get back to you on that.

**Comment by jkeiser** [comment]
@jaymzh OK, here's a build that *definitely* has the fix:

http://opscode-omnibus-packages-current.s3.amazonaws.com/el/6/x86_64/chef-12.5.0%2B20150922164016-1.el6.x86_64.rpm

**Comment by jaymzh** [comment]
OK, this fixes part of it. Now we have a slightly related issue with new_resource... if we call `new_resource.foo` where we have defined:
`attribute :foo, kind_of => String, :default => nil, :name_attribute => true`

it comes back as nil even though a name was passed into the resource

**Comment by coderanger** [comment]
We should probably make that be an actual error, `default` and `name_attribute` are a semantic conflict. Allowing both seems like a bug IMO.

**Comment by jaymzh** [comment]
agreed, but different bug

**Comment by jkeiser** [comment]
Filing a bug now. It's a weird case, and I'm not sure how I feel about it. Closing this one, though, since it sounds like it's fixed.
