### ISSUE TITLE
chef-client run failed after upgrade to 12.4

### ISSUE THREAD

**Issue by StaymanHou** [chef/chef#3634]
12.3 worked fine.
affected chef-client version: 12.4
does not appear to be related to any specific cookbook or recipe
environment: Ubuntu 12.04

```
[2015-07-02T20:35:47+00:00] DEBUG: NoMethodError: undefined method `match' for {:enable=>true}:Hash
/opt/chef/embedded/apps/chef/lib/chef/resource.rb:1181:in `defined_at'
/opt/chef/embedded/apps/chef/lib/chef/resource.rb:572:in `run_action'
/opt/chef/embedded/apps/chef/lib/chef/runner.rb:49:in `run_action'
/opt/chef/embedded/apps/chef/lib/chef/runner.rb:81:in `block (2 levels) in converge'
/opt/chef/embedded/apps/chef/lib/chef/runner.rb:81:in `each'
/opt/chef/embedded/apps/chef/lib/chef/runner.rb:81:in `block in converge'
/opt/chef/embedded/apps/chef/lib/chef/resource_collection/resource_list.rb:83:in `block in execute_each_resource'
/opt/chef/embedded/apps/chef/lib/chef/resource_collection/stepable_iterator.rb:116:in `call'
/opt/chef/embedded/apps/chef/lib/chef/resource_collection/stepable_iterator.rb:116:in `call_iterator_block'
/opt/chef/embedded/apps/chef/lib/chef/resource_collection/stepable_iterator.rb:85:in `step'
/opt/chef/embedded/apps/chef/lib/chef/resource_collection/stepable_iterator.rb:104:in `iterate'
/opt/chef/embedded/apps/chef/lib/chef/resource_collection/stepable_iterator.rb:55:in `each_with_index'
/opt/chef/embedded/apps/chef/lib/chef/resource_collection/resource_list.rb:81:in `execute_each_resource'
/opt/chef/embedded/apps/chef/lib/chef/runner.rb:80:in `converge'
/opt/chef/embedded/apps/chef/lib/chef/client.rb:654:in `block in converge'
/opt/chef/embedded/apps/chef/lib/chef/client.rb:649:in `catch'
/opt/chef/embedded/apps/chef/lib/chef/client.rb:649:in `converge'
/opt/chef/embedded/apps/chef/lib/chef/client.rb:688:in `converge_and_save'
/opt/chef/embedded/apps/chef/lib/chef/client.rb:269:in `run'
/opt/chef/embedded/apps/chef/lib/chef/application.rb:270:in `block in fork_chef_client'
/opt/chef/embedded/apps/chef/lib/chef/application.rb:258:in `fork'
/opt/chef/embedded/apps/chef/lib/chef/application.rb:258:in `fork_chef_client'
/opt/chef/embedded/apps/chef/lib/chef/application.rb:224:in `block in run_chef_client'
/opt/chef/embedded/apps/chef/lib/chef/local_mode.rb:39:in `with_server_connectivity'
/opt/chef/embedded/apps/chef/lib/chef/application.rb:212:in `run_chef_client'
/opt/chef/embedded/apps/chef/lib/chef/application/client.rb:402:in `block in interval_run_chef_client'
/opt/chef/embedded/apps/chef/lib/chef/application/client.rb:392:in `loop'
/opt/chef/embedded/apps/chef/lib/chef/application/client.rb:392:in `interval_run_chef_client'
/opt/chef/embedded/apps/chef/lib/chef/application/client.rb:382:in `run_application'
/opt/chef/embedded/apps/chef/lib/chef/application.rb:60:in `run'
/opt/chef/embedded/apps/chef/bin/chef-client:26:in `<top (required)>'
/usr/bin/chef-client:53:in `load'
/usr/bin/chef-client:53:in `<main>'
```

**Comment by lamont-granquist** [comment]
What is the rest of the context?  What resource is blowing up there and what is the rest of the output?

**Comment by jkeiser** [comment]
I can imagine this could happen if the user calls:

```ruby
some_resource 'blah', enable: true do
end
````

But I'm rather surprised at the idea it worked before.

**Comment by jkeiser** [comment]
Ah!  It looks like the code used to ignore anything beyond the first argument when declaring a resource, and now we don't.  This is a weird error, but the fix I'd first want to make would cause it to error out when you do the above rather than crash in the weird way.

**Comment by jkeiser** [comment]
Ignoring the parameter seems like ungood behavior.

**Comment by coderanger** [comment]
Guessing this is a side effect from some copy pasta of a definition?

**Comment by jkeiser** [comment]
@coderanger #3638 has a fix which should self-explain what I was talking about.

12.3 worked because our method_missing ignored arguments: https://github.com/chef/chef/blob/12.3-stable/lib/chef/dsl/recipe.rb#L44

**Comment by jkeiser** [comment]
By "fix," I mean clear error message in this case.  It is also possible to deprecate, if we so desire.

**Comment by jkeiser** [comment]
I've updated the fix to actually fix the bug, and emit a warning, so the recipe should continue to work as before, with a deprecation warning.

**Comment by StaymanHou** [comment]
Great. Thanks
