### ISSUE TITLE
Undefined method up_to_date thrown by Chef 12.16.42 in custom resource

### ISSUE THREAD

**Issue by jeunito** [chef/chef#5593]
## Description

Upon upgrading to Chef 12.16.42 it throws the following errors when calling a custom resource which previously worked in Chef 12.15.19: 

```
NoMethodError
  -------------
  undefined method `up_to_date' for nil:NilClass
```

## Platform Version

Ubuntu 16.04

## Replication Case

Run the following recipe: 

```
kernel_module "zfs" do
  action :install
end
```

This depends on the following [custom resource provider](https://github.com/Shopify/chef-kernel_module). 

There seems to be no indication that this is a bug in the custom resource. 

## Client Output

```
  ================================================================================
  Error executing action `install` on resource 'kernel_module[zfs]'
  ================================================================================

  NoMethodError
  -------------
  undefined method `up_to_date' for nil:NilClass

  Resource Declaration:
  ---------------------
  # In /var/chef/cache/cookbooks/modules_test/recipes/default.rb

    2: kernel_module "zfs" do
    3:   action :install
    4: end

  Compiled Resource:
  ------------------
  # Declared in /var/chef/cache/cookbooks/modules_test/recipes/default.rb:2:in `from_file'

  kernel_module("zfs") do
    action [:install]
    retries 0
    retry_delay 2
    default_guard_interpreter :default
    declared_type :kernel_module
    cookbook_name "modules_test"
    recipe_name "default"
    load_dir "/etc/modules-load.d"
    modname "zfs"
  end

  Platform:
  ---------
  x86_64-linux
```

**Comment by jeunito** [comment]
Interestingly this isn't replicable on Virtualbox and Docker. I am only able to replicate this on baremetal servers.

**Comment by lamont-granquist** [comment]
@adamleff the `up_to_date` method seems related to data collector stuff?

@jeunito the stacktrace.out would be more helpful than anything else in tracking this down, i can't tell from your bug report where the error is at all.

**Comment by adamleff** [comment]
Yeah, I'm willing to bet it's part of the Data Collector stuff, but should be fixed by #5571.

**Comment by jeunito** [comment]
@lamont-granquist here is a stacktrace https://gist.github.com/jeunito/95ead072504ad67be27f797d0fd129c5

**Comment by adamleff** [comment]
@jeunito Thanks for the stacktrace. This should be fixed in 12.17.22 or later and will be available in the next `stable` release of Chef (which I think will happen next week).

In the meantime, can you try the latest `current` release and see if this is fixed for you? If it's not, I want to understand why. You can install the latest `current` release via omnitruck like this:

```
curl https://omnitruck.chef.io/install.sh | bash -s -- -c current
```

**Comment by jeunito** [comment]
@adamleff it works in the `current` release. Thanks.

**Comment by jeunito** [comment]
@adamleff do you know why this issue wasn't replicable on Docker/Virtualbox?

**Comment by adamleff** [comment]
@jeunito I honestly have no idea, it's still a bit of a mystery. If you can provide us some reproduction steps (i.e. what OS, what cookbook/recipe, etc.) I'm happy to try to solve the mystery. But the fix in #5571 will at least stop the exceptions from happening.

I'm going to close this, but don't hesitate to post another comment with repro steps and I'll take another look.

**Comment by jeunito** [comment]
@adamleff the reproduction steps are in the description. A colleague noticed the issue happening on a baremetal server and I tried replicating it on Docker/Virtualbox but to no avail.

**Comment by adamleff** [comment]
Sorry, missed that. I'll take a look as time allows, but the main issue that was contributing to this should be fixed. Thanks again for the report!
