### ISSUE TITLE
18.4.2 windows_service property "description": NoMethodError

### ISSUE THREAD

**Issue by rjhornsby** [chef/chef#14229]
## Description

As of 18.4.2, the `windows_service` resource does not process the `description` property/argument correctly. Example code:
```
windows_service service_name do
  binary_path_name startup_command
   name new_resource.agent_name
   description "#{new_resource.agent_name} agent"
   delayed_start false
   timeout 30
   action %i[create enable start]
 end
```

The error is:

```
NoMethodError
-------------
undefined method `description' for #<struct Struct::ServiceConfigInfo service_type="own process",
 start_type="auto start", error_control="normal", binary_path_name="C:/vault/vault.exe agent 
-config=C:/vault/config/agent.hcl ", load_order_group="", tag_id=0, dependencies=[], 
service_start_name="LocalSystem", display_name="vault">

            current_resource.description(config_info.description)           if new_resource.description
                                                    ^^^^^^^^^^^^
```

Removing the `description` property from the resource works around the problem.

## Chef Version
18.4.2 (was working in 18.3.0)

## Platform Version
```
      System Info:
      ------------
      chef_version=18.4.2
      platform=windows
      platform_version=10.0.17763
      ruby=ruby 3.1.2p20 (2022-04-12 revision 4491bb740a) [x64-mingw-ucrt]
```

## Stacktrace
```
C:/cinc-project/cinc/embedded/lib/ruby/gems/3.1.0/gems/chef-18.4.2-x64-mingw-ucrt/lib/chef/provider/service/windows.rb:77:in `load_current_resource'
C:/cinc-project/cinc/embedded/lib/ruby/gems/3.1.0/gems/chef-18.4.2-x64-mingw-ucrt/lib/chef/provider.rb:228:in `run_action'
C:/cinc-project/cinc/embedded/lib/ruby/gems/3.1.0/gems/chef-18.4.2-x64-mingw-ucrt/lib/chef/resource.rb:601:in `block in run_action'
```

**Comment by bdwyertech** [comment]
This is a result of https://github.com/chef/chef/pull/14064. `ServiceConfigInfo` does not include a description field, do we even test things anymore?

<img width="784" alt="image" src="https://github.com/chef/chef/assets/2973273/7cd44bc4-29ad-4d14-81cb-44a9703ead5e">


https://github.com/chef/win32-service/blob/67a0f7ac46a5e0332d95867f1ee2e7cd733b9117/lib/win32/service.rb#L206-L217

**Comment by joeldq** [comment]
This is also on Chef 17.10.122

**Comment by bdwyertech** [comment]
> This is also happening on Chef 17.10.122

Makes sense.  They backported the change I referenced into 17 here.  https://github.com/chef/chef/pull/14151
