### ISSUE TITLE
FATAL: NoMethodError: undefined method `each_char' for [“bundle”, “install”]:Array Did you mean? each_cons

### ISSUE THREAD

**Issue by sankareswarg3** [chef/chef#8998]
I am working on Chef to automate a deployment procedures, I have configured everything on my Chef environment.

OS & Version details are as below
Chef Server - RHEL7
Chef Workstation - Windows 7 Professional
Chef node : Windows 2016 Server Datacenter

Chef Development Kit Version: 3.3.23
chef-client version: 14.5.33
berks version: 7.0.6
kitchen version: 1.23.2
inspec version: 2.2.112

Created a sample cookbook just to create a test.txt file in node where we are executing chef-client. Below is the files resource which we are using on recipe.

```
`file 'C:\\temp\\something.txt' do
  rights :read, 'Everyone'
  #rights :full_control, 'DOMAIN\\User'
  action :create
end`
```

Getting below error on running chef-client on remote node

```
Running handlers:
[2019-10-15T19:25:18+08:00] ERROR: Running exception handlers
Running handlers complete
[2019-10-15T19:25:18+08:00] ERROR: Exception handlers complete
Chef Client failed. 0 resources updated in 15 seconds
[2019-10-15T19:25:18+08:00] INFO: Sending resource update report (run-id: 5ea7d4d4-2cd4-4456-bcf4-5458fbfdb31d)
[2019-10-15T19:25:19+08:00] FATAL: Stacktrace dumped to c:/chef/cache/chef-stacktrace.out
[2019-10-15T19:25:19+08:00] FATAL: Please provide the contents of the stacktrace.out file if you file a bug report
[2019-10-15T19:25:19+08:00] FATAL: NoMethodError: undefined method 'each_char' for ["bundle", "install"]:Array
Did you mean?  each_cons
```
I don't have much knowledge on ruby. attached stacktrace.out
[chef-stacktrace.txt](https://github.com/chef/chef/files/3730681/chef-stacktrace.txt)

**Comment by vsingh-msys** [comment]
Hey, thanks for reporting the issue. it is regression and fixes is available in latest version of chefdk.  
Fixed in https://github.com/chef/chef/pull/8974

**Comment by sankareswarg3** [comment]
Hi @vsingh-msys ,

I am still not able to run chef-client , even after upgrading chefDK with latest version.
ChefDK version: 4.4.45

**Comment by tas50** [comment]
I don't think this is the same issue as #8975 since that bug never made its way into DK

**Comment by vsingh-msys** [comment]
@tas50 I was referring to chef-14 regression which was fixed in #8974 . As reported in https://github.com/chef/chef/issues/8970

```
NoMethodError: undefined method `each_char' for ["bundle", "install"]:Array
```



@sankareswarg3  could you please let me know the node chef-client version. if your node still has chef-client 14.5.33.

then need to update your chef-client version either chef-14 latest (14.14.25) or you can upgrade to chef-15

Thanks!

**Comment by lamont-granquist** [comment]
That stacktrace is from chef-14.14.14, you need to upgrade to 14.14.25.

You are also using the omnibus-chef install in C:\opscode\chef, not out of chef-dk.

Closing as a dup of #8974
