### ISSUE TITLE
12.1.0 Release Regressions

### ISSUE THREAD

**Issue by btm** [chef/chef#3107]
@chef/maintainers,
 
We had a significant number of package resource/provider regressions in 12.1.0 and we've been spending a significant amount of time fixing/testing/releasing recently due to these. We need to hold a public post-mortem and talk about what we're going to do in the future to reduce this risk. Chef Inc has a post-mortem process that we've used publicly in the past, especially with supermarket. We could start with that. Thoughts?

---
## Post-mortem

Meeting Report: https://gist.github.com/btm/641d3b0ec331ac34fbe9

---

## Regression status

| Issue | Release Fixed | Description |
| -------- | -------------------- | ---------------- |
| https://github.com/chef/chef/issues/3008 | 12.1.1 | yum source bug |
| https://github.com/chef/chef/issues/3009 | Closed | strings sent to run_action don't work |
| https://github.com/chef/chef/issues/3011 | 12.1.1 | easy_install broke due missing command mixin |
| https://github.com/chef/chef/issues/3018 | 12.1.1 | knife search -a output wrong |
| https://github.com/chef/chef/issues/3022 | 12.1.2 | homebrew provider broken |
| https://github.com/chef/chef/issues/3030 | Closed |  yum version bug |
| https://github.com/chef/chef/issues/3059 | 12.1.2 | different yum source bug? |
| https://github.com/chef/chef/issues/3084 | None | undefined local variable or method `client_pem' |
| https://github.com/chef/chef/issues/3096 | 12.2.0* | openbsd package bug |
| https://github.com/chef/chef/issues/3108 | None | aix source bug |
| https://github.com/chef/chef/issues/3105 | Closed | easy_install source bug |
| https://github.com/chef/chef/issues/3112 | None | SmartOS "pkgin install" failing |
| https://github.com/chef/chef/issues/3115 | None | Option name must be a kind of String! |

## Technical Debt / Features

| Issue | Release Fixed | Description |
| -------- | -------------------- | ---------------- |
| https://github.com/chef/chef/issues/3014 | None | Deprecate Chef::Mixin::Command |
| https://github.com/chef/chef/issues/3040 | None | multi-package resource should take a hash for name/version |
| https://github.com/chef/chef/issues/3075 | None | Raise exception when source passed to multi-package resource |

**Comment by lamont-granquist** [comment]
#2722 is completely unrelated to the #2692 multipackage change.

**Comment by lamont-granquist** [comment]
#3105 looks like a dup of the package source issue
#3096 its unclear if this is a regression or not
#3059 is a dup of the package source issue
#3008 is the package source issue cause by #2692
#3009 was closed not a bug
#3022 is the mac homebrew bug caused by #2722
#3011 was cause by the removal of the Chef::Mixin::Command at the top level (#2924)
#2914 was caught before shipping during testing
#3108 looks like a dup of the package source issue

The inclusion of multiple duplicate issues, issues that were caught before release and one wontfix/notabug makes it look a lot worse than it was.

The three real bugs that we shipped are also all unrelated even though they all hit the package providers on the same release by coincidence.  Of the three changes #2722 and #2924 don't remotely fall under the level of change which could be considered for RFC.  Those are largely internal changes and the issues went unnoticed through peer review and testing and were only identified in retrospect (the provides syntax was due largely to derp on my part and getting how Providers and Resources resolve via the provides line confused in my own head, while everyone who reviewed the run_command-to-shell_out change missed the possible external API change by dropping the include and that was simply reverted).

Its also unlikely that we would have caught the multipackage source bug no matter what up front process we went through.  We had no testing around that, and the root cause of the problem was convoluted code in define_resource_requirements which was refactored in order to try to make it more understandable, while introducing a subtle error, in the absence of having any test coverage around the explicit local source use case.  None of those errors are caught by more RFC process.

**Comment by jonlives** [comment]
I think having a post mortem for this would be a valuable exercise, and I'd be happy to participate.

**Comment by btm** [comment]
@lamont-granquist the scope being discussed is at least "package regressions". If anything, I'd expand that to all 12.1.0 regressions, rather than reduce it to just regressions caused by #2692. The point is that 12.1.0 had more regressions than we should be allowing ourselves, we need to do better, and we should talk about how we're going to do that.

I'll start by suggesting we have a 12.1.0 release post-mortem around the same time of day that we have our IRC meetings but on a different day, like a Wednesday, and use IRC like we do for our weekly meetings as well. We can use the template that we use at Chef Inc to guide us. I've put that in a gist: https://gist.github.com/btm/7cb421f5fe7d1003083a. We can use this issue to start putting together these details and discuss corrective actions together in the post-mortem.

* Description
* Timeline
* Contributing Factor(s)
* Stabilization Steps
* Impact

**Comment by jdmundrawala** [comment]
#3105 has multiple bugs showing. First, it ignores `source`, which i'm going to count that as a bug. This is unrelated to 12.1. The second is what happens when a package cannot be found. 12.0.3 correctly fails the run, which 12.1 says everything is ok.

#3096 is a new feature, so it's not a regression. However, if we go back to the merge commit, this code correctly works. Even if we validated on all platforms we have CI for, this would not have been caught, because this is not one of our supported platforms.

#3059 is on us. Our testing is not complete, this is definitely a regression. This is one source bug. It is reporting that it correctly installed everything when it did not.

#3008 #3030 Are a different source bug.

#3011 we changes a public interface that our own code relied on. We don't actually run this resource in any of our functional testing, however something like running rspec with verify partial doubles could have caught this

#3108 Is similar to to #3059. In 12.1, we report that the resource is already up to date, when it's not. While this is a regression, it regressed from already brokenness. In 12.0.3, this resource just fails the run. Since this wasn't reported, I can only imaging nobody is running this? I do think the new behavior is worse though as it says everything is good when it is in fact not.


These being enumerated, I think we need to fix #3105, and we should probably be good citizens and fix #3096 even though it's not one of our supported platforms.
I'm going to say #3108 is of less urgency as it was broken before and I've seen no issues filed against it.

I'm still waiting to hear back about our solaris package provider. Archlinux was ok, however it also does not use source when it is provided. 

Things that I don't think have been touched yet:
- ips
- paludis
- portage
- smartos
- zypper

I have not personally tested homebrew and macports, however am I correct in saying that this case has been covered by others?

**Comment by btm** [comment]
In today's regular IRC meeting we agreed that we should have a post-mortem using Google Hangouts or Zoom at 9am PDT / Noon EDT /  1600 UTC on Tuesday 3/24. That's the same time of day we usually have IRC meetings but it's on the upcoming Tuesday. I'll send out information to the chef-dev list and then share it here later in the day.

**Comment by tas50** [comment]
It should also be noted that multi-package in 12.1 broke the rbenv_gem provider in the popular rbenv cookbook.  This is due to the rbenv_gem provider extending the now heavily refactored rubygems provider in core chef.  The rbenv cookbook probably shouldn't have done that, but it still burned a ton of people and doesn't yet have a fix.

https://github.com/fnichol/chef-rbenv/issues/107
and
https://github.com/chef/chef/issues/3115

**Comment by nathenharvey** [comment]
We will also host a follow-up meeting to discuss some of the impacts that this release had on another tool in the community, Chef Sugar.  

This meeting will be held on [Wednesday, March 25 at 17:00 UTC / 13:00 EDT / 10:00 PDT](http://www.timeanddate.com/worldclock/fixedtime.html?msg=chef_gem+and+chef_sugar+release+post+mortem&iso=20150325T13&p1=1928&am=50).

Chef 12.1.0 introduced some [chef_gem resource warnings](https://www.chef.io/blog/2015/02/17/chef-12-1-0-chef_gem-resource-warnings/).  This caused a [compatibility issue with Chef Sugar](https://github.com/sethvargo/chef-sugar/issues/89).

During this meeting we will explore ways to improve our collaboration and 
identify changes like this earlier in the process.

This will be run as a blameless postmortem where we hope to capture some key 
learnings and action items.

All follow up action items will be assigned to a team/individual before the end 
of the meeting. If the item is not going to be top priority leaving the meeting, 
we won't make it a follow up item.


Join from PC, Mac, iOS or Android:  
https://chef.zoom.us/j/3809339711
 
Or join by phone:

* +1 (415) 762-9988 or +1 (646) 568-7788 (US Toll)
* +1 (855) 703-8985 (US/Canada Toll Free)  
* Meeting ID: 380 933 9711  

* International numbers available: https://chef.zoom.us/zoomconference 


Or join from a H.323/SIP room system: 

* Dial: 162.255.37.11 (US West) or 162.255.36.11 (US East) 
* Meeting ID: 380 933 9711 
    
[Wednesday, March 25 at 17:00 UTC / 13:00 EDT / 10:00 PDT](http://www.timeanddate.com/worldclock/fixedtime.html?msg=chef_gem+and+chef_sugar+release+post+mortem&iso=20150325T13&p1=1928&am=50)

**Comment by charlesjohnson** [comment]
We didn't get to #3040 in the meeting today (That's fine, had plenty going on to fill the hour), but I do want to make sure it gets followup.

**Comment by lamont-granquist** [comment]
This hasn't been touched in awhile.  If there's still outstanding issues those probably need to get prioritized and assigned a milestone and get into backlogs.  This issue isn't very actionable now.
