### ISSUE TITLE
Package resource fails chefspec on RHEL starting with Chef 12.18.

### ISSUE THREAD

**Issue by rhass** [chef/chef#5769]
## Description

Package resource fails chefspec on RHEL starting with Chef 12.18.

## Chef Version

- Introduced in cset 626213cb2d6f1e4de18c6f29573e3aa34ed76cef (identified via `git bisect`)

## Platform Version

Ubuntu Linux 16.04 

## Replication Case

- [ ] On a Linux box, clone the omnibus cookbook
- [ ] Checkout v5.1.0
- [ ] With the latest stable chefdk installed (or current), run `chef exec rake spec`

## Stacktrace

```
================================================================================
Recipe Compile Error in /tmp/d20170130-17827-1otmbna/cookbooks/omnibus/recipes/_compile.rb
================================================================================

NoMethodError
-------------
undefined method `split' for nil:NilClass

Cookbook Trace:
---------------
  /tmp/d20170130-17827-1otmbna/cookbooks/omnibus/recipes/_compile.rb:73:in `from_file'

Relevant File Content:
----------------------
/tmp/d20170130-17827-1otmbna/cookbooks/omnibus/recipes/_compile.rb:

 66:      end
 67:    end
 68:  elsif rhel?
 69:    # Make sure tar is installed. It's missing from some CentOS Docker images:
 70:    #
 71:    #   https://github.com/CentOS/sig-cloud-instance-images/issues/4
 72:    #
 73>>   package 'tar'
 74:    package 'bzip2'
 75:  elsif windows?
 76:    node.default['seven_zip']['syspath'] = true
 77:    include_recipe 'seven_zip::default'
 78:  end
 79:  
```

**Comment by scotthain** [comment]
Example full stack trace of repro case: https://gist.github.com/scotthain/c8a415dd3fb52922dd3113d04c1b185c

**Comment by lamont-granquist** [comment]
looks like `ENV['PATH']` is nil.  i'm sort of inclined to think that this isn't a chef/chef bug and that chefspec needs to supply a halfway sane path variable, but not sure.

**Comment by thommay** [comment]
I tend to agree that this seems like a chefspec bug. Either way we should resolve it before the next client release.

**Comment by lamont-granquist** [comment]
Ultimately this is a bug with chefspec not knowing how to stub the ResourceResolver.  I went down the road of thinking that chefspec should try to stub `which("dnf")` but that seems a bit insane.  Also thought through the idea of putting all that information into ohai, but that would be too eager binding in chef (you might install dnf, then try to use it, and have to reload ohai, also just, ugh...).   So it feels like chefspec should be stubbing at the level of the ResourceResolver, either in the class itself or having chefspec do a `allow(Chef::Resource).to receive(:resource_for_node).with(:package, anything).and_return(Chef::Provider::YumPackage)`.  Anyway chef/chef is just using a feature we introduced back in 12.0.0 its just that chefspec was
never made smart enough to deal with it.  The only problem with this approach is we need a whole new set of data like fauxhai around what the dynamic ResourceResolver returns on a given platform for a given chef-client version, with the ability for the chefspec user to twiddle the dial.

**Comment by lamont-granquist** [comment]
I just looked through the chefspec code and can't find where or how its building Chef::Resource objects, i had though it called `Chef::Resource.resource_for_node` but now I can't find it.  Its clearly building them somehow, but I couldn't track it down.

First step would be finding where that code is.

**Comment by lamont-granquist** [comment]
Another thing is that Centos 7 will optionally be getting DNF and we really do need this feature.  This definitely isn't a regression or bug in core chef, chefspec needs to change.

**Comment by rhass** [comment]
I am going to close this for now since we know it not to be a chef bug
