### ISSUE TITLE
chef-shell failures with Ruby 3.4

### ISSUE THREAD

**Issue by ramereth** [chef/chef#15066]
While doing some testing with building Cinc Client 19, I noticed the following issue with chef-shell:

```
$ cinc-shell --version
<internal:/opt/cinc/embedded/lib/ruby/3.4.0/rubygems/core_ext/kernel_require.rb>:136:in 'Kernel#require': cannot load such file -- irb/ext/save-history (LoadError)
        from <internal:/opt/cinc/embedded/lib/ruby/3.4.0/rubygems/core_ext/kernel_require.rb>:136:in 'Kernel#require'
        from /opt/cinc/embedded/lib/ruby/gems/3.4.0/gems/chef-bin-19.1.39/bin/cinc-shell:25:in '<top (required)>'
        from /usr/bin/cinc-shell:198:in 'Kernel.load'
        from /usr/bin/cinc-shell:198:in '<main>'
```

Looking at the code I see the following:
``` ruby
require "irb/ext/save-history"
```

When I comment out this line I get the following:
```
/opt/cinc/embedded/lib/ruby/gems/3.4.0/gems/chef-19.1.39/lib/chef/shell.rb:63:in 'Shell.start': undefined method 'delete' for nil (NoMethodError)
        from /opt/cinc/embedded/lib/ruby/gems/3.4.0/gems/chef-bin-19.1.39/bin/cinc-shell:31:in '<top (required)>'
        from /usr/bin/cinc-shell:198:in 'Kernel.load'
        from /usr/bin/cinc-shell:198:in '<main>'
```

The code block referenced is:
```ruby
# FUGLY HACK: irb gives us no other choice.
irb_help = [:help, :irb_help, IRB::ExtendCommandBundle::NO_OVERRIDE]
IRB::ExtendCommandBundle.instance_variable_get(:@ALIASES).delete(irb_help)
```

Looks like this has been in chef for 15 years! 070d3ece708.

Not sure if this is needed anymore, but probably needs to be refactored to work with Ruby 3.4.
